### ISSUE TITLE
Controller not recognized

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#514]
**Describe the bug**
I created a very simple extension with only one table which is including 2 input fields.  
The controller is not found instead I only see the error in the log:  
```
Mon, 11 Oct 2021 00:08:20 +0000 [ALERT] request="8b39e8bc7395c" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler":
Oops, an error occurred! Code: 20211011000820d0dddec4 - {
"exception":"TYPO3\\CMS\\Extbase\\Mvc\\Exception: 
The default controller for extension \"Test\" and plugin \"Test\" can not be determined. 
Please check for TYPO3\\CMS\\Extbase\\Utility\\ExtensionUtility::configurePlugin() in your ext_localconf.php. in /var/www/html/typo3app/private/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php:256
Stack trace:
#0 /var/www/html/typo3app/private/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php(211): TYPO3\\CMS\\Extbase\\Mvc\\Web\\RequestBuilder->resolveControllerClassName(Array)
#1 /var/www/html/typo3app/private/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php(47): TYPO3\\CMS\\Extbase\\Mvc\\Web\\RequestBuilder->build()
#2 /var/www/html/typo3app/private/typo3/sysext/extbase/Classes/Core/Bootstrap.php(183): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()
#3 /var/www/html/typo3app/private/typo3/sysext/extbase/Classes/Core/Bootstrap.php(173): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()
#4 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)
#5 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(5690): call_user_func_array(Array, Array)
#6 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(43): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')
#7 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(828): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)
#8 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(742): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)
#9 /var/www/html/typo3app/private/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php(193): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array, 'tt_content.list...')
#10 /var/www/html/typo3app/private/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php(170): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper::renderContentObject(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer), Array, 'tt_content.list...', 'test_test')
#11 /var/www/html/typo3app/var/cache/code/fluid_template/Standard_action_list_2dc1bf9fdaa7b89e736e62f416200fd25b7de994.php(66): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#12 /var/www/html/typo3app/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(78): Standard_action_list_2dc1bf9fdaa7b89e736e62f416200fd25b7de994->{closure}()
#13 /var/www/html/typo3app/var/cache/code/fluid_template/Standard_action_list_2dc1bf9fdaa7b89e736e62f416200fd25b7de994.php(91): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#14 /var/www/html/typo3app/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(260): Standard_action_list_2dc1bf9fdaa7b89e736e62f416200fd25b7de994->section_62bce9422ff2d14f69ab80a154510232fc8a9afd(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#15 /var/www/html/typo3app/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(173): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('Main', Array, true)
#16 /var/www/html/typo3app/var/cache/code/fluid_template/layout_Default_html_49772cc93e16d93162707584c60d1d0d8a326783.php(1143): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#17 /var/www/html/typo3app/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(78): layout_Default_html_49772cc93e16d93162707584c60d1d0d8a326783->{closure}()
#18 /var/www/html/typo3app/var/cache/code/fluid_template/layout_Default_html_49772cc93e16d93162707584c60d1d0d8a326783.php(1665): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#19 /var/www/html/typo3app/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(201): layout_Default_html_49772cc93e16d93162707584c60d1d0d8a326783->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))
#20 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php(358): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()
#21 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php(108): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()
#22 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(828): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)
#23 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(742): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)
#24 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(723): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.contentElem...')
#25 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/CaseContentObject.php(47): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'list')
#26 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(828): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render(Array)
#27 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(742): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject), Array)
#28 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(723): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, 'tt_content')
#29 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentContentObject.php(95): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, '')
#30 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(828): TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject->render(Array)
#31 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(742): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject), Array)
#32 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(687): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CONTENT', Array, '100')
#33 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Http/RequestHandler.php(231): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)
#34 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Http/RequestHandler.php(197): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageBodyContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))
#35 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Http/RequestHandler.php(133): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController), Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#36 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/OutputCompression.php(48): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#37 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))
#38 /var/www/html/typo3app/private/typo3conf/ext/crawler/Classes/Middleware/CrawlerInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#39 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): AOE\\Crawler\\Middleware\\CrawlerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#40 /var/www/html/typo3app/private/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelDataPersister.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#41 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelDataPersister->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#42 /var/www/html/typo3app/private/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelRenderer.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#43 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelRenderer->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#44 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/ContentLengthResponseHeader.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#45 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#46 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(69): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#47 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#48 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(86): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#49 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#50 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(108): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#51 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#52 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/PageArgumentValidator.php(131): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#53 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#54 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#55 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#56 /var/www/html/typo3app/private/typo3/sysext/adminpanel/Classes/Middleware/SqlLogging.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#57 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#58 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(106): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#59 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#60 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(80): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#61 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#62 /var/www/html/typo3app/private/typo3conf/ext/crawler/Classes/Middleware/FrontendUserAuthenticator.php(73): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#63 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): AOE\\Crawler\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#64 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(94): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#65 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#66 /var/www/html/typo3app/private/typo3/sysext/redirects/Classes/Http/Middleware/RedirectHandler.php(81): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#67 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#68 /var/www/html/typo3app/private/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelInitiator.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#69 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#70 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(77): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#71 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#72 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#73 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#74 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#75 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#76 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(65): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#77 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#78 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(64): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#79 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#80 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#81 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\
ormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#82 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#83 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#84 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#85 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#86 /var/www/html/typo3app/private/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#87 /var/www/html/typo3app/private/typo3/sysext/core/Classes/Http/AbstractApplication.php(97): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#88 /var/www/html/www/index.php(26): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#89 /var/www/html/www/index.php(27): {closure}()
#90 {main}"}
```
I tried to use variations in ext_localconf.php but without success.  
**[EDIT:]**  
this is the configuration of the plugin in ext_localconf.php:  
```
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        'Test',
        'Test',
        [
            \Abc\Test\Controller\TestController::class => 'index, list, show'
        ],
        // non-cacheable actions
        [
            \Abc\Test\Controller\TestController::class => ''
        ]
    );
```

**To Reproduce**
The extension is attached, try to run it.  
[test.zip](https://github.com/FriendsOfTYPO3/extension_builder/files/7323153/test.zip)

**Expected behavior**
That at least the list-view shows some output or creates an error related to the view, but not the controller.

**Screenshots**
![image](https://user-images.githubusercontent.com/999146/136806601-cad203ee-95ef-4681-8124-acf7dcdf2dda.png)

**TYPO3 Version**
Composer setup, tested on the two versions:    
TYPO3: 10.4.21 + 10.4.20  

**Extension Builder Version:**
Version ExtensionBuilder: 10.0.1

**Comment by DavidBruchmann** [comment]
All configuration is in the extension and actions are probably not verified yet as long as not even the controller is recognized.  
Tracing it down in the code is a pain, On some things I can't even say what the code is doing in detail and if I could influence it with some parameters in TypoScript or in ext_localconf.php.

**Comment by DavidBruchmann** [comment]
Seems on my local PC something is really wired, on the server everything works fine.  
I close it as there is no indication for any bug.
